# .github/workflows/notify-api.yml

name: 🔔 Notificar API após novo modelo

on:
  workflow_run:
    workflows: ["📈 Treinamento e Relatório MLflow"]
    types:
      - completed

jobs:
  notify-api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 🔔 Enviar notificação para API
        run: |
          curl -X POST ${{ secrets.API_DEPLOY_HOOK }}
